spring:
  application:
    name: sekill-mall
server:
  port: 8081
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.10.10.123:3306/mall-pms
    driver-class-name: com.mysql.cj.jdbc.Driver